language: cpp

compiler:
  - clang
  - g++

os:
  - linux
  - osx
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq gfortran
 - if [[ "$TARGET_BOX" == "LINUX32" ]]; then sudo apt-get install -qq  gcc-multilib gfortran-multilib; fi

script: cmake -DBUILD_TEST=ON -H. -Bbuild && cmake --build build -- -j3
